name: test

on: [push]

jobs:
  build:

    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3
      - name: setup
        uses: actions/setup-python@v2
        with:
          python-version: '3.10.7'
      - name: dependencies
        run: |
          cd  ${{ inputs.working_directory }}
          pip install -r requirements.txt
      - name: Test with pytest
        run: |
          pytest -r -w
